version: '2'
services:
  nestjs:
    build: ..
    command: ./wait-for-it.sh -t 0 mysql:3306 -- node dist/main.js
    container_name: nestjs_rest_graphql
    depends_on:
      - mysql
    environment:
      NODE_ENV: development
    networks:
      - bd-tier
    ports:
      - "3000:3000"
    restart: on-failure:10
    volumes:
      - ./wait-for-it.sh:/usr/src/app/wait-for-it.sh
      - ../development.env:/usr/src/app/development.env

  mysql:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: nestjs_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: graphql_nest
      MYSQL_USER: graphql_nest
      MYSQL_PASSWORD: graphql_nest
    image: mysql:5.7
    networks:
      - bd-tier
    restart: on-failure:10
    volumes:
      - nestjs_graphql_persistance:/var/lib/mysql

networks:
  bd-tier:
    driver: bridge

volumes:
  nestjs_graphql_persistance:
    driver: local
